FROM nginx:stable-alpine

# Copy the custom Nginx configuration
COPY ./app.conf /etc/nginx/conf.d/default.conf

# Copy the entire project so Nginx can serve static assets from the public folder
COPY . /var/www/html