services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: npontu-app
    restart: unless-stopped
    working_dir: /var/www/html
    networks:
      - npontu-network

  web:
    image: nginx:stable-alpine
    container_name: npontu-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - npontu-network
    depends_on:
      - app

networks:
  npontu-network:
    driver: bridge
