services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: npontu-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80:80"
    networks:
      - npontu-network

networks:
  npontu-network:
    driver: bridge
