app = "npontutrack-activity-tracker"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_URL = "https://npontutrack-activity-tracker.fly.dev"
  TRUSTED_PROXIES = "*"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "cookie"
  CACHE_STORE = "database"
  DB_CONNECTION = "mysql"
  DB_HOST = "127.0.0.1"
  DB_DATABASE = "npontu"
  DB_USERNAME = "sail"
  DB_PASSWORD = "password"

[[mounts]]
  source = "npontutrack_storage"
  destination = "/var/www/html/storage"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    path = "/up"
    protocol = "http"
    timeout = "2s"