services:
  # Native PHP Web Service (No Docker)
  - type: web
    name: npontu-native
    runtime: static
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "touch database/database.sqlite && php artisan migrate --force --seed && php artisan serve --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        sync: false
      - key: APP_KEY
        sync: false # Set this in the Render Dashboard manually
      - key: LOG_CHANNEL
        value: stderr
      - key: TRUSTED_PROXIES
        value: "*"
      - key: APP_URL
        value: "https://npontu-native.onrender.com"
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
